name: build

on: [ workflow_dispatch, pull_request ]
  
env:
  COVERAGE_COVERAGE_FILE_PATH: ./coverage/lcov.info

jobs:
  test:
    runs-on: macos-latest
    environment: github-actions-release
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Unit-Tests Build + Coverlet
        run: |
          dotnet tool install --global coverlet.console
          dotnet add $PROJECT_PATH package coverlet.collector
          dotnet build $PROJECT_PATH
          dotnet test --collect:"XPlat Code Coverage" --settings $COVERLET_SETTINGS --results-directory:"$COVERAGE_DIRECTORY" $PROJECT_PATH
          mv $COVERAGE_DIRECTORY/*/$COVERAGE_INFO_FILENAME ${{ env.COVERAGE_COVERAGE_FILE_PATH }}
        env:
          PROJECT_PATH: ./source/EduCATS.UnitTests/EduCATS.UnitTests.csproj
          COVERLET_SETTINGS: ./source/coverlet.runsettings
          COVERAGE_DIRECTORY: ./coverage
          COVERAGE_INFO_FILENAME: coverage.info          
        
      - name: Codecov Deploy
        uses: codecov/codecov-action@v3.1.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ${{ env.COVERAGE_COVERAGE_FILE_PATH }}
          os: macos

  build:
    runs-on: macos-13
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Setup Xamarin
        run: |
          brew install --cask xamarin-ios
          brew install --cask xamarin-android
          ls ~/Library/Caches/Homebrew
          ls ~/Library/Caches/Homebrew/Casks
        
      - name: NuGet Cache
        uses: actions/cache@v3.3.1
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      
      - name: NuGet Restore
        run: nuget restore $SOLUTION_PATH
        env:
          SOLUTION_PATH: ./source/EduCATS.sln
        
      - name: Build iOS        
        run: MSBuild /t:Build /p:Configuration=$CONFIGURATION /p:Platform=$PLATFORM $PROJECT_PATH
        env:
          CONFIGURATION: Release
          PLATFORM: iPhoneSimulator
          PROJECT_PATH: ./source/EduCATS.iOS/EduCATS.iOS.csproj
          
      - name: Build Android
        run: MSBuild /t:Build /p:Configuration=$CONFIGURATION $PROJECT_PATH
        env:
          CONFIGURATION: Release
          PROJECT_PATH: ./source/EduCATS.Android/EduCATS.Android.csproj
